### ISSUE TITLE
Problem with fonts on "eu-noth-1"

### ISSUE THREAD

**Issue by nickdenisenko** [brandonlim-hs/fonts-aws-lambda-layer#1]
I've deployed lambda instance with layers on "**eu-west-1**":

```
  layers:
    - arn:aws:lambda:eu-west-1:347599033421:layer:wkhtmltopdf-0_12_6:1
    - arn:aws:lambda:eu-west-1:347599033421:layer:amazon_linux_fonts:1
```

And generated PDF **looks good**.

But on "**eu-north-1**" the same lambda instance with layers:

```
  layers:
    - arn:aws:lambda:eu-north-1:347599033421:layer:wkhtmltopdf-0_12_6:1
    - arn:aws:lambda:eu-north-1:347599033421:layer:amazon_linux_fonts:1
```

And generated PDF has a **problem with fonts** – each character looks like a square. E.g:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1898063/95212007-4e333b00-07fe-11eb-8a37-bac86aad9007.png">

**Comment by nickdenisenko** [comment]
@brandonlim-hs can you help me please? do you have any idea??

**Comment by brandonlim-hs** [comment]
Hi @PEKTOP, just confirming if you have added the environment variable `FONTCONFIG_PATH=/opt/etc/fonts`?

**Comment by nickdenisenko** [comment]
> Hi @PEKTOP, just confirming if you have added the environment variable `FONTCONFIG_PATH=/opt/etc/fonts`?

Thank you! It was my mistake that I forgot about the environment variable – Everything is ok now 😊
