### ISSUE TITLE
i want to download one Stix fonts layer zip file how to download it..please help me with this

### ISSUE THREAD

**Issue by Dheerajsrinu** [brandonlim-hs/fonts-aws-lambda-layer#3]
I couldn't download this layer because i don't have permissions 
so can you specify how to download a zip file for this layers

**Comment by brandonlim-hs** [comment]
Hi @Dheerajsrinu 
What have you tried to do to download the layer, and what was the error message? More information always helps with the investigation. :)


From my side, looks like I am able to download this layer from another AWS account. Running the below:
```
aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-1:347599033421:layer:stix-fonts:1 --region us-east-1 --profile another_account --query Content.Location --output text
```
Resulted with the URL to download the layer:
```
https://prod-04-2014-layers.s3.us-east-1.amazonaws.com/snapshots/347599033421/stix-fonts-[REDACTED]
```


Reference:
- https://stackoverflow.com/questions/56614037/how-to-download-aws-lambda-layer

**Comment by Dheerajsrinu** [comment]
Thankyou for your reply

Now I got to download the file

previously I was using the command without the region ..that is the reason I was getting that error I guess 
`aws lambda get-layer-version-by-arn --arn "arn:aws:lambda:us-west-2:347599033421:layer:amazon_linux_fonts:1" --profile secondprofile`

Thanks once again.
